language: php 
dist: trusty
php:
    - 5.6
    - 7.0
    - hhvm-3.15
install: composer install
script: ./run_tests.sh
before_deploy: php build_phar.php
deploy:
    provider: releases
    file: "dicto.phar"
    skip_cleanup: true
    on:
        tags: true
